### ISSUE TITLE
What should I do with CORS?

### ISSUE THREAD

**Issue by Aver005** [mumu-lhl/duckduckgo-ai-chat#2]
I've already tried a lot of different query variations, but no.

![image](https://github.com/user-attachments/assets/b5be6134-4a39-47f0-a201-e3efb7578414)

**Comment by mumu-lhl** [comment]
I'm not sure how to do that either. Maybe you can wait for someone else to reply.

**Comment by FurryR** [comment]
Using a CORS proxy like Cloudflare Worker might help.
