### ISSUE TITLE
duckduckgo api 回复出现[DONE]标志符导致的error

### ISSUE THREAD

**Issue by MarchPhantasia** [mumu-lhl/duckduckgo-ai-chat#5]
如果对[DONE]字符串parse处理的话会出现error
![image](https://github.com/user-attachments/assets/2fd79e83-110c-4a85-96e3-cc041ec6f9e3)

**Comment by MarchPhantasia** [comment]
我在解决issue https://github.com/wangyz1999/LiteLoaderQQNT-GPT-Reply/issues/12 的时候遇到了此问题，问题截图如下
![873f3d5fd1d0e2567750f09a44846e90](https://github.com/user-attachments/assets/cde4baa1-9706-497f-8ad2-3b26a101cbfe)

使用示例的demo程序错误如下：
![image](https://github.com/user-attachments/assets/4788cd63-4f5f-463e-9046-408ad1fe507e)

**Comment by MarchPhantasia** [comment]
#6 已解决

**Comment by mumu-lhl** [comment]
v3.0.1 已包含这个补丁
